- hosts: all
  connection: local
  vars:
    username: root
    password: Password
    host: 192.168.99.51
    port: 22
    ansible_python_interpreter: /Users/rick446/src/Python-Classes/cox/env/bin/python
    netconf:
      username: root
      password: Password
      host: 192.168.99.51
      port: 22

  tasks:
  - name: Gather some JunOS facts
    junos_facts: "username={{username}} password={{password}} host={{host}} port={{port}}"
  - name: Print a message
    debug: "msg='The version is {{version_info}}'"
  - name: run a set of commands
    junos_command:
      commands: ['show version', 'show ip route']
      provider: "{{ netconf }}"
  - name: run a command with a conditional applied to the second command
    junos_command:
      commands:
        - show version
        - show interfaces fxp0
      waitfor:
        - "result[1].interface-information.physical-interface.name eq fxp0"
      provider: "{{ netconf }}"
