- hosts: all
  remote_user: python
  become: yes
  tasks:
  - name: Let the sudo group use sudo without a password
    lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
  - name: Create python .ssh
    file: path=/home/python/.ssh state=directory owner=python group=python mode=0700
  - name: Install python authorized_keys
    copy: src=../id_rsa.pub dest=/home/python/.ssh/authorized_keys owner=python group=python mode=0600

